### ISSUE TITLE
Failed to authenticate error

### ISSUE THREAD

**Issue by bweave** [CopilotC-Nvim/CopilotChat.nvim#115]
I'm getting the following error on all CopilotChat commands:

```
error caught in async handler '/Users/brianweaver/.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat:command:CopilotChat [['What does this mean?']]'
Traceback (most recent call last):
  File "/Users/brianweaver/.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat/copilot_plugin.py", line 47, in copilot_agent_cmd
    self.vsplit_chat_handler.chat(args[0], file_type, code)
  File "/Users/brianweaver/.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat/handlers/vsplit_chat_handler.py", line 62, in chat
    super().chat(prompt, filetype, code, self.nvim.current.window.handle)
  File "/Users/brianweaver/.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat/handlers/chat_handler.py", line 74, in chat
    self._add_chat_messages(
  File "/Users/brianweaver/.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat/handlers/chat_handler.py", line 282, in _add_chat_messages
    self.copilot.authenticate()
  File "/Users/brianweaver/.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat/copilot.py", line 93, in authenticate
    raise Exception(f"Failed to authenticate: {self.token}")
Exception: Failed to authenticate: {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest'}
```

Here's my relevant packer config:

```
  use({ "github/copilot.vim" })
  use({
    "CopilotC-Nvim/CopilotChat.nvim",
    config = function()
      require("CopilotChat").setup({
        show_help = "yes",         -- Show help text for CopilotChatInPlace, default: yes
        debug = true,              -- Enable or disable debug mode, the log file will be in ~/.local/state/nvim/CopilotChat.nvim.log
        disable_extra_info = "no", -- Disable extra information (e.g: system prompt) in the response.
        language = "English",      -- Copilot answer language settings when using default prompts. Default language is English.
        build = function()
          vim.notify("Please update the remote plugins by running ':UpdateRemotePlugins', then restart Neovim.")
        end,
      })
    end,
  })

```

I'm not sure what to make of `Failed to authenticate` since `Copilot status` reports it's enabled and active. `:checkhealth CopilotChat` is all green, too. Any ideas?

**Comment by gptlang** [comment]
Do you have access to CopilotChat? See if you get an error with the VSCode extension.

**Comment by bweave** [comment]
@gptlang Thanks for the quick response. Yep, I have access to CopilotChat in VSCode.

**Comment by gptlang** [comment]
>   use({ "github/copilot.vim" })

I just checked this issue out again and see that you're using GitHub's Copilot.vim. We've really only done testing with `zbirenbaum/copilot.lua`. Could you try authenticating with that instead?

**Comment by bweave** [comment]
Sorry for the delay here. I get the same `Failed to authenticate` with `zbirenbaum/copilot.lua`.

**Comment by jellydn** [comment]
Hi @bweave Could you try with v2 or canary branch? Thanks.

**Comment by bweave** [comment]
Canary branch is working for me! 🎉 Thanks!
