### ISSUE TITLE
error in rplugin after CopilotChat migrate python to lua.

### ISSUE THREAD

**Issue by jowu598** [CopilotC-Nvim/CopilotChat.nvim#190]
After CopilotChat refactor using lua, type `CopilotChat` I got error: 
```
Traceback (most recent call last):
  File "/home/yj/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat/copilot_plugin.py", line 35, in copilot_agent_cmd
    self.vsplit_chat_handler.chat(args[0], file_type, code)
  File "/home/yj/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat/handlers/vsplit_chat_handler.py", line 58, in chat
    super().chat(prompt, filetype, code, self.nvim.current.window.handle)
  File "/home/yj/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat/handlers/chat_handler.py", line 65, in chat
    self._add_chat_messages(system_prompt, prompt, code, filetype, model)
  File "/home/yj/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat/handlers/chat_handler.py", line 250, in _add_chat_messages
    for token in self.copilot.ask(
  File "/home/yj/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat/copilot.py", line 107, in ask
    if self.token.get("expires_at") <= round(time.time()):
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```
Why rplugin is still work?

here is my config
```
python:3.11
pynvim:0.5.0
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

**Comment by deathbeam** [comment]
Did you ran `:UpdateRemotePlugins` like the migration guide says?
