### ISSUE TITLE
"Unterminated string literal" when :UpdateRemotePlugins

### ISSUE THREAD

**Issue by guivazcabral** [CopilotC-Nvim/CopilotChat.nvim#71]
Just pulled the latest version of the plugin, and when running `:UpdateRemotePlugins` I get the following error:

```
Encountered SyntaxError loading plugin at /Users/guilherme/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat: unterminated string literal (detected at line 151) (copilot.py, line 151)
Traceback (most recent call last):
  File "/Users/guilherme/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pynvim/plugin/host.py", line 193, in _load
    module = _handle_import(directory, name)
  File "/Users/guilherme/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pynvim/plugin/host.py", line 40, in _handle_import
    return importlib.import_module(name)
  File "/Users/guilherme/.pyenv/versions/3.10.13/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "/Users/guilherme/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat/copilot.py", line 151
    response.status_code, f"Unknown error: {
                          ^
SyntaxError: unterminated string literal (detected at line 151)

remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/guilherme/.local/share/nvim/rplugin.vim
```

Please advise. Thanks!

**Comment by guivazcabral** [comment]
locally manually edited the file to bring line 152 to 151 and it solved the issue. I guess the string cannot be broken into multiple lines like that? (don't know, not really a python dev 😅 )
https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/9bfb0b7f0c7595f04d6491053fe538dda70d32ed/rplugin/python3/CopilotChat/copilot.py#L151-L152

**Comment by jellydn** [comment]
Thanks, @guivazcabral for the report. Could you try again with latest commit? It should work now.

**Comment by guivazcabral** [comment]
> Thanks, @guivazcabral for the report. Could you try again with latest commit? It should work now.

Confirming it works, thanks for the quick fix!

**Comment by jellydn** [comment]
Great. Good to hear that.

I've just setup https://pre-commit.ci/ for this repository to prevent this issue happened, fyi.
